// @generated by protoc-gen-es v1.8.0 with parameter "target=js+dts"
// @generated from file rc/loyalty/types/v1/type.proto (package rc.loyalty.type.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum rc.loyalty.type.v1.TransactionType
 */
export const TransactionType = /*@__PURE__*/ proto3.makeEnum(
  "rc.loyalty.type.v1.TransactionType",
  [
    {no: 0, name: "TRANSACTION_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "TRANSACTION_TYPE_EARNED", localName: "EARNED"},
    {no: 2, name: "TRANSACTiON_TYPE_REDEEMED", localName: "REDEEMED"},
    {no: 3, name: "TRANSACTiON_TYPE_RETURNED", localName: "RETURNED"},
    {no: 4, name: "TRANSACTiON_TYPE_EXPIRED", localName: "EXPIRED"},
  ],
);

/**
 * @generated from message rc.loyalty.type.v1.PaginatedTransactions
 */
export const PaginatedTransactions = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.type.v1.PaginatedTransactions",
  () => [
    { no: 1, name: "transactions", kind: "message", T: Transaction, repeated: true },
    { no: 2, name: "has_prev_page", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "has_next_page", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message rc.loyalty.type.v1.Transactions
 */
export const Transactions = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.type.v1.Transactions",
  () => [
    { no: 1, name: "transactions", kind: "message", T: Transaction, repeated: true },
  ],
);

/**
 * @generated from message rc.loyalty.type.v1.Transaction
 */
export const Transaction = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.type.v1.Transaction",
  () => [
    { no: 1, name: "identity_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "transaction_type", kind: "enum", T: proto3.getEnumType(TransactionType) },
    { no: 3, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "amount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
);

