// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file rc/loyalty/mgmt/v1/mgmt.proto (package rc.loyalty.mgmt.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ActivateMembershipRequest, ConfigureLoyaltyRequest, GetActivityRequest, GetLoyaltyRequest, GetStatsRequest, Loyalty, Membership, Stats } from "./mgmt_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { PaginatedTransactions } from "../../types/v1/types_pb.js";

/**
 * @generated from service rc.loyalty.mgmt.v1.LoyaltyMgmtService
 */
export const LoyaltyMgmtService = {
  typeName: "rc.loyalty.mgmt.v1.LoyaltyMgmtService",
  methods: {
    /**
     * @generated from rpc rc.loyalty.mgmt.v1.LoyaltyMgmtService.ConfigureLoyalty
     */
    configureLoyalty: {
      name: "ConfigureLoyalty",
      I: ConfigureLoyaltyRequest,
      O: Loyalty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rc.loyalty.mgmt.v1.LoyaltyMgmtService.GetLoyalty
     */
    getLoyalty: {
      name: "GetLoyalty",
      I: GetLoyaltyRequest,
      O: Loyalty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rc.loyalty.mgmt.v1.LoyaltyMgmtService.ActivateMembership
     */
    activateMembership: {
      name: "ActivateMembership",
      I: ActivateMembershipRequest,
      O: Membership,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rc.loyalty.mgmt.v1.LoyaltyMgmtService.GetActivity
     */
    getActivity: {
      name: "GetActivity",
      I: GetActivityRequest,
      O: PaginatedTransactions,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rc.loyalty.mgmt.v1.LoyaltyMgmtService.GetStats
     */
    getStats: {
      name: "GetStats",
      I: GetStatsRequest,
      O: Stats,
      kind: MethodKind.Unary,
    },
  }
} as const;

