// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file rc/loyalty/mgmt/v1/mgmt.proto (package rc.loyalty.mgmt.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { TransactionType } from "../../types/v1/types_pb.js";

/**
 * @generated from enum rc.loyalty.mgmt.v1.LoyaltyType
 */
export const LoyaltyType = /*@__PURE__*/ proto3.makeEnum(
  "rc.loyalty.mgmt.v1.LoyaltyType",
  [
    {no: 0, name: "LOYALTY_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "LOYALTY_TYPE_POINTS_PER_MONETARY_UNIT", localName: "POINTS_PER_MONETARY_UNIT"},
    {no: 2, name: "LOYALTY_TYPE_CASH_BACK", localName: "CASH_BACK"},
  ],
);

/**
 * @generated from enum rc.loyalty.mgmt.v1.LoyaltyParticipants
 */
export const LoyaltyParticipants = /*@__PURE__*/ proto3.makeEnum(
  "rc.loyalty.mgmt.v1.LoyaltyParticipants",
  [
    {no: 0, name: "LOYALTY_PARTICIPANTS_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "LOYALTY_PARTICIPANTS_ALL_CUSTOMERS", localName: "ALL_CUSTOMERS"},
    {no: 2, name: "LOYALTY_PARTICIPANTS_ONLY_STORE_ACCOUNTS", localName: "ONLY_STORE_ACCOUNTS"},
  ],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.ConfigureLoyaltyRequest
 */
export const ConfigureLoyaltyRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.ConfigureLoyaltyRequest",
  () => [
    { no: 1, name: "community_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "loyalty_type", kind: "enum", T: proto3.getEnumType(LoyaltyType) },
    { no: 3, name: "participants", kind: "enum", T: proto3.getEnumType(LoyaltyParticipants) },
    { no: 4, name: "points_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "cashback_percentage", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 6, name: "points_earned", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 7, name: "monetary_unit_spent", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 8, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "cashback_redemption_points", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 10, name: "discount_per_points_redeemed", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 11, name: "points_expiry", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 12, name: "reward_online", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 13, name: "reward_pos", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "exclude_coupon_discounts", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 15, name: "include_shipping", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.GetLoyaltyRequest
 */
export const GetLoyaltyRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.GetLoyaltyRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identifier" },
    { no: 2, name: "community_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identifier" },
  ],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.ActivateMembershipRequest
 */
export const ActivateMembershipRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.ActivateMembershipRequest",
  () => [
    { no: 1, name: "loyalty_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identifier" },
    { no: 2, name: "community_id", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "identifier" },
    { no: 3, name: "community_membership_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "is_active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.Loyalty
 */
export const Loyalty = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.Loyalty",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "community_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "loyalty_type", kind: "enum", T: proto3.getEnumType(LoyaltyType) },
    { no: 4, name: "participants", kind: "enum", T: proto3.getEnumType(LoyaltyParticipants) },
    { no: 5, name: "points_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "cashback_percentage", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 7, name: "points_earned", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 8, name: "monetary_unit_spent", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 9, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "cashback_redemption_points", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 11, name: "discount_per_points_redeemed", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 12, name: "points_expiry", kind: "scalar", T: 13 /* ScalarType.UINT32 */, opt: true },
    { no: 13, name: "reward_online", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 14, name: "reward_pos", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 15, name: "exclude_coupon_discounts", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 16, name: "include_shipping", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.Membership
 */
export const Membership = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.Membership",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "loyalty_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "community_membership_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "is_active", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.GetActivityRequest
 */
export const GetActivityRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.GetActivityRequest",
  () => [
    { no: 1, name: "transaction_type", kind: "enum", T: proto3.getEnumType(TransactionType), opt: true },
    { no: 2, name: "page_number", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "community_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "page_size", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.GetStatsRequest
 */
export const GetStatsRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.GetStatsRequest",
  [],
);

/**
 * @generated from message rc.loyalty.mgmt.v1.Stats
 */
export const Stats = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.mgmt.v1.Stats",
  () => [
    { no: 1, name: "points_cashback_earned", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "points_cashback_redeemed", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "redemption_rate", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "revenue", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "revenue_currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

