// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file rc/loyalty/portal/v1/portal.proto (package rc.loyalty.portal.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Balance, GetActivityRequest, GetBalanceRequest } from "./portal_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { PaginatedTransactions } from "../../types/v1/types_pb.js";

/**
 * @generated from service rc.loyalty.portal.v1.LoyaltyService
 */
export const LoyaltyService = {
  typeName: "rc.loyalty.portal.v1.LoyaltyService",
  methods: {
    /**
     * @generated from rpc rc.loyalty.portal.v1.LoyaltyService.GetBalance
     */
    getBalance: {
      name: "GetBalance",
      I: GetBalanceRequest,
      O: Balance,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc rc.loyalty.portal.v1.LoyaltyService.GetActivity
     */
    getActivity: {
      name: "GetActivity",
      I: GetActivityRequest,
      O: PaginatedTransactions,
      kind: MethodKind.Unary,
    },
  }
} as const;

