// @generated by protoc-gen-es v1.9.0 with parameter "target=js+dts"
// @generated from file rc/loyalty/portal/v1/portal.proto (package rc.loyalty.portal.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { TransactionType } from "../../types/v1/types_pb.js";

/**
 * @generated from message rc.loyalty.portal.v1.GetBalanceRequest
 */
export const GetBalanceRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.portal.v1.GetBalanceRequest",
  [],
);

/**
 * @generated from message rc.loyalty.portal.v1.GetActivityRequest
 */
export const GetActivityRequest = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.portal.v1.GetActivityRequest",
  () => [
    { no: 1, name: "transaction_type", kind: "enum", T: proto3.getEnumType(TransactionType), opt: true },
    { no: 2, name: "page_number", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "page_size", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ],
);

/**
 * @generated from message rc.loyalty.portal.v1.Balance
 */
export const Balance = /*@__PURE__*/ proto3.makeMessageType(
  "rc.loyalty.portal.v1.Balance",
  () => [
    { no: 1, name: "amount", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

